# Generated by Django 2.0.5 on 2018-05-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taizhou',
            name='GPS_lng',
            field=models.TextField(blank=True),
        ),
    ]
