# Generated by Django 2.0.5 on 2018-05-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_taizhou_gps_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taizhou',
            name='GPS_lat',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='taizhou',
            name='GPS_lng',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='taizhou',
            name='avg',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='taizhou',
            name='howsell',
            field=models.TextField(null=True),
        ),
    ]
